export enum ProjectCategory {
  ALL = 'All',
  MOTION_GRAPHICS = 'Motion Graphics',
  WEB_APPS = 'Web Apps',
  VIDEO_PRODUCTION = 'Video Production',
  SOCIAL_MEDIA = 'Social Media',
  DOCUMENTARY = 'Documentary'
}

export interface Project {
  id: string;
  title: string;
  thumbnail: string;
  duration: string;
  views: string;
  uploadDate: string;
  category: ProjectCategory;
  description: string; // Static description
  aiDescription?: string; // Generated by Gemini
  tags: string[];
  skills: string[];
  videoUrl?: string; // For demo purposes
}

export interface Experience {
  id: string;
  role: string;
  company: string;
  period: string;
  location: string;
  description: string[];
}

export interface Comment {
  id: string;
  user: string;
  avatar: string;
  content: string;
  likes: number;
  timestamp: string;
  isPinned?: boolean;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model' | 'system';
  text: string;
  timestamp: number;
  isThinking?: boolean;
}
